name: Create a new bug report
title: "Quick description"
description: report a new bug here
projects: "lypitech/2"
body:
  - type: input
    id: bug_description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: "ex: The button is misaligned on the homepage."
    validations:
      required: true
  - type: textarea
    attributes:
      label: How to Reproduce
      description: "Steps to reproduce the behavior:"
      placeholder: Tell us what you see!
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
  - type: input
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: "ex: The button should be centered on the homepage."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: |
        ex:
        - Screenshots
        - logs
        - Any other relevant information.
  - type: checkboxes
    attributes:
      label: Pre-submission checklist
      description: "Please ensure you have completed the following before submitting your bug report:"
      options:
        - label: I have SET the appropriate label
          required: true
        - label: I have SET the appropriate milestone
          required: true
        - label: I have UNSET the issue tag
          required: true
    validations:
      required: true
